evolution:
  archive_size: 10
  population_size: 2
  mutation_rate: 0.15
  selection_method: "top_k"

evaluation:
  subset_sizes: [5, 10]          # light local stages
  promotion_threshold: 0.3
  max_evaluations_per_generation: 2

rewards:
  alpha_tests_passed: 0.6
  beta_constitution_score: 0.3
  gamma_diff_complexity: 0.1

safety:
  sandbox_enabled: true
  max_execution_time: 120
  resource_limits:
    cpu_percent: 80
    memory_mb: 4096
